baseURL = "https://spurlin.dev"
languageCode = "en-us"
title = "spurlin.dev"
theme = "neocities-revival"

# Content organization
enableRobotsTXT = true
enableGitInfo = true

# Pagination
[pagination]
  pagerSize = 10

# Suppress warnings
ignoreLogs = ['warning-goldmark-raw-html']

# Site parameters
[params]
  # Basic Info
  author = "Matt Spurlin"
  description = "Welcome to the retro web! Developer, designer, and TIC-80 enthusiast building pixel-perfect experiences with the SWEETIE-16 palette."
  
  # Retro Features
  visitorCount = "001337"
  underConstruction = false
  enableGuestbook = false
  
  # TIC-80 Customization
  pixelPerfect = true
  enableSoundEffects = true
  showStarfield = true

# Menu configuration
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github-dark"
    lineNos = true
    codeFences = true

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

# Privacy settings
[privacy]
  [privacy.x]
    disable = false
    enableDNT = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
