baseURL = "https://example.com"
languageCode = "en-us"
title = "PICO-8 Web"
theme = "neocities-revival"

# Site parameters
[params]
  # Basic Info
  author = "Matt Spurlin"
  description = "Welcome to the retro web! A nostalgic journey through 90s aesthetics with modern PICO-8 design."
  
  # Retro Features
  visitorCount = "001337"
  underConstruction = false
  enableGuestbook = false
  
  # PICO-8 Customization
  pixelPerfect = true
  enableSoundEffects = true
  showStarfield = true

# Navigation menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series" 